In [9]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print("Array : ",arr)
arr.shape=[3,3]
print("Array after changing its dimension to 3 by 3 : \n",arr)
lst=arr.tolist()
print("List : \n",lst)

Array :  [1 2 3 4 5 6 7 8 9]
Array after changing its dimension to 3 by 3 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
List : 
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
