In [3]:
import numpy as np
a=np.arange(9).reshape(3,3)
print("...Matrix A...\n",a)
print("Rank of matrix A = ",np.linalg.matrix_rank(a))

...Matrix A...
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Rank of matrix A =  2
