In [15]:
from sklearn.datasets import load_iris
from sklearn import metrics
x,y=load_iris(return_X_y=True)  #returns x and y values as numpy arrays

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.30,random_state=0)

from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
ypred=gnb.fit(xtrain,ytrain).predict(xtest)

#to find the accuracy
print("Naive Bayes score from the dataset = ",gnb.score(xtest,ytest),"\n")


metrics.accuracy_score(ytest,ypred)
print("Predicted values of y : \n",ypred,"\n")


from sklearn.metrics import confusion_matrix
print("Confusion matrix of the dataset : \n",confusion_matrix(ytest,ypred),"\n")

#for new value of x............................................................................

x_new=[[5,5,4,4]]
y_new=[[2]]
y_pred_new=gnb.fit(xtrain,ytrain).predict(x_new)
print("Predicted output for x_new = ",y_pred_new)
print("Confusion matrix of the new values : \n",confusion_matrix(y_pred_new,y_new),"\n")
print("Naive Bayes score for new values = ",gnb.score(x_new,y_new),"\n")

Naive Bayes score from the dataset =  1.0 

Predicted values of y : 
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1 1 1 2 0 2 0 0] 

Confusion matrix of the dataset : 
 [[16  0  0]
 [ 0 18  0]
 [ 0  0 11]] 

Predicted output for x_new =  [2]
Confusion matrix of the new values : 
 [[1]] 

Naive Bayes score for new values =  1.0 

