In [1]:
import numpy as np
x=np.identity(5)
print("5 by 5 identity matrix :\n",x)

5 by 5 identity matrix :
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
