In [11]:
import numpy as np
x=np.arange(9).reshape(3,3)
print("...Array...\n",x)

header = 'col1 col2 col3'
np.savetxt('temp.txt',x,fmt="%d",header=header)
result=np.loadtxt('temp.txt')
print("\nAfter loading the content of the file\n",result)

...Array...
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

After loading the content of the file
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
