In [3]:
import numpy as np
print("Enter the elements of first 2 by 2 matrix : ")
e1=list(map(int,input().split()));
x=np.array(e1).reshape(2,2)
print("Enter the elements of second 2 by 2 matrix : ")
e2=list(map(int,input().split()));
y=np.array(e2).reshape(2,2)
print("...First matrix...\n",x,"\n...Second matrix...\n",y)
print("Dot product of the matrices : \n",np.dot(x,y))

Enter the elements of first 2 by 2 matrix : 
2 3 4 5
Enter the elements of second 2 by 2 matrix : 
4 5 6 7
...First matrix...
 [[2 3]
 [4 5]] 
...Second matrix...
 [[4 5]
 [6 7]]
Dot product of the matrices : 
 [[26 31]
 [46 55]]
