In [4]:
import numpy as np
a=np.arange(6).reshape(2,3)
print("...Matrix A...\n",a)
print("...Matrix A transpose...\n",np.transpose(a))

...Matrix A...
 [[0 1 2]
 [3 4 5]]
...Matrix A transpose...
 [[0 3]
 [1 4]
 [2 5]]
